node{
    stage('Scm checkout'){
        def gitexec = tool name: 'Default', type: 'git'
        git branch: 'dev', credentialsId: 'cap10-github', url: 'https://github.com/cap10/mynhakamylife.git'
    }
    stage('Build'){
       def mvnHome = "/usr/share/maven"
       def mvnCMD = "${mvnHome}/bin/mvn"
       sh "${mvnCMD} -B -DskipTests clean package"
    }


  /* stage("build & SonarQube analysis") {
    agent any
    steps {
      withSonarQubeEnv('sonar-polad') {
        sh 'mvn clean package sonar:sonar'
      }
    }
} */
    stage('Build docker image'){
    sh 'docker-compose build --no-cache --force-rm'
    }
stage('tagging image'){
        sh 'docker tag polad-nhaka-dev:latest cap10/myrepository:polad-nhaka-dev'
        }
        stage('Push new image'){
               withCredentials([string(credentialsId: 'docker-pwd', variable: 'dockerHubPwd')]) {
                          // some block
                   sh "docker login -u cap10 -p ${dockerHubPwd}"
               }
            sh 'docker push cap10/myrepository:polad-nhaka-dev'
        }

         stage('Clean up'){
            sh 'docker system prune -a'
        }

}
