spring:

  zipkin:
    base-url: http://192.168.1.200:9411/
  sleuth:
    sampler:
      probability: 1
server:
  port: 8765

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://192.168.1.185:8761/eureka/
zuul:
  sensitiveHeaders: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000


ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000