package zw.co.jugaad.audittrailservice.permissions;

public enum Authorities {

    CREATE_AGENT,
    VIEW_AGENT,
    UPDATE_AGENT,
    DELETE_AGENT,

    CREATE_AUDIT_TRAIL,
    VIEW_AUDIT_TRAIL,
    UPDATE_AUDIT_TRAIL,
    DELETE_AUDIT_TRAIL,

    CREATE_BANK,
    VIEW_BANK,
    UPDATE_BANK,
    DELETE_BANK,

    CREATE_BILLER,
    VIEW_BILLER,
    UPDATE_BILLER,
    DELETE_BILLER,

    CREATE_DEVICE,
    VIEW_DEVICE,
    UPDATE_DEVICE,
    DELETE_DEVICE,

    APPROVE_DISBURSEMENT,
    BULK_REGISTRATION,
    INITIATE_DISBURSEMENT,


    CREATE_OPERATOR,
    VIEW_OPERATOR,
    UPDATE_OPERATOR,
    DELETE_OPERATOR,

    CREATE_PRODUCT,
    VIEW_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,

    CREATE_SUBSCRIBER,
    VIEW_SUBSCRIBER,
    UPDATE_SUBSCRIBER,
    DELETE_SUBSCRIBER,

    CREATE_AGENT_COMMISSION,
    VIEW_AGENT_COMMISSION,
    UPDATE_AGENT_COMMISSION,
    DELETE_AGENT_COMMISSION,

    CREATE_AGENT_FEE,
    VIEW_AGENT_FEE,
    UPDATE_AGENT_FEE,
    DELETE_AGENT_FEE,


    CREATE_AGENT_LIMIT,
    VIEW_AGENT_LIMIT,
    UPDATE_AGENT_LIMIT,
    DELETE_AGENT_LIMIT,


    CREATE_AGENT_PROFILE,
    VIEW_AGENT_PROFILE,
    UPDATE_AGENT_PROFILE,
    DELETE_AGENT_PROFILE,

    CREATE_AGENT_VELOCITY,
    VIEW_AGENT_VELOCITY,
    UPDATE_AGENT_VELOCITY,
    DELETE_AGENT_VELOCITY,

    CREATE_SUBSCRIBER_FEE,
    VIEW_SUBSCRIBER_FEE,
    UPDATE_SUBSCRIBER_FEE,
    DELETE_SUBSCRIBER_FEE,


    CREATE_SUBSCRIBER_LIMIT,
    VIEW_SUBSCRIBER_LIMIT,
    UPDATE_SUBSCRIBER_LIMIT,
    DELETE_SUBSCRIBER_LIMIT,


    CREATE_SUBSCRIBER_PROFILE,
    VIEW_SUBSCRIBER_PROFILE,
    UPDATE_SUBSCRIBER_PROFILE,
    DELETE_SUBSCRIBER_PROFILE,

    CREATE_SUBSCRIBER_VELOCITY,
    VIEW_SUBSCRIBER_VELOCITY,
    UPDATE_SUBSCRIBER_VELOCITY,
    DELETE_SUBSCRIBER_VELOCITY,

    CREATE_TRANSACTION_TYPE,
    VIEW_TRANSACTION_TYPE,
    UPDATE_TRANSACTION_TYPE,
    DELETE_TRANSACTION_TYPE,

    VIEW_TRANSACTION_REPORT,
    VIEW_TRANSACTION_SUMMARY









}
