spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: false
      max-file-size: 10MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/mynhakamylife?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Africa/Harare
    username: 'developer'
    password: 'ch@ng3itDev'
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    database: MYSQL
    hibernate:
      ddl-auto: update

    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  jackson:
    serialization:
      fail-on-empty-beans: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8100

security:
  oauth2:
    resource:
      jwt:
        key-value: JWTKey@123
        key-uri: http://localhost:9090/oauth/token_key
      id: 'carInventory'
    client:
      client-id: appclient
      client-secret: appclient@123

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql: TRACE

logging.logstash:
  enabled: true
  url: 62.171.154.168:5601

upload-dir: ./uploads
templates-dir: ./templates
purge.cron.expression: 0 0 5 * * ?
maturity.cron.expression: 0 0 5 * * ?
lapsed.cron.expression: 0 0 5 * * ?
individual.cron.expression: 0 46 12 * * ?
employer.cron.expression: 0 18 17 * * ?

client.delight.email: takaiteyi@gmail.com
claim.admin.email: takaiteyi@gmail.com
premium.admin.email: takaiteyi@gmail.com
policy.admin.email: takaiteyi@gmail.com
ceo.email: takaiteyi@gmail.com
finance.email: takaiteyi@gmail.com

accident:
  for:
    every:
      thousand: 0.6
  waiting: 3
  grace: 30
  clawbackPeriod: 9

funeral:
  for:
    every:
      thousand: 0.6
  waiting: 3
  grace: 30
  clawbackPeriod: 12

comprehensive:
  for:
    every:
      thousand: 0.6
  waiting: 3
  grace: 30
  clawbackPeriod: 12

savings:
  for:
    every:
      thousand: 0.6
  waiting: 3
  grace: 30
  clawbackPeriod: 4

cash:
  import:
    format: '{0},{1},{2},{3}'